language: python
python:
- '3.7'
services:
- docker
before_install:
- pip install codecov
- docker pull markusgoetz/heat
- docker run -dt --name unittest -v $PWD:/heat markusgoetz/heat
- pip install pre-commit
install:
- pre-commit run --all-files
- docker exec -t unittest /bin/bash -c '. /root/.bashrc && pip install --progress-bar
  off -e .[hdf5,netcdf] && pip list'
script:
- |
  docker exec -t unittest /bin/bash -c '. /root/.bashrc && \
    for i in {1..4}; do mpirun --mca btl_vader_single_copy_mechanism none --mca btl ^openib --allow-run-as-root -np $i coverage run --source=heat --parallel-mode -m pytest heat/ || exit; done && \
    mpirun --mca btl_vader_single_copy_mechanism none --mca btl ^openib --allow-run-as-root -np 7 coverage run --source=heat --parallel-mode -m pytest heat/ && \
    coverage combine && \
    coverage report && \
    coverage xml'
after_success:
- codecov
before_deploy:
- sudo chown -R $USER:$USER *
deploy:
  provider: pypi
  user: __token__
  password:
    secure: FVXVdbTdhhxDg1TM/0xnxIwio28CBDhGKfSepiAm5kX1RDa2+Sc1HdFeP7cu1mqdeASrngNIOwaq4H9UPguoSfrBEIM1U8QSG/i4F10vXip8gzBgxrf5KrIBneILzwxnWf5D78lIyVntLJNJDH8UdZE39Fpd3JJtw6Aq3SnuA1Vr61clALdbJrqwCipoGY23VDrWpfhwEqytvaBay3qvCjFk6B3KZ8RTBoabwGEz9cE0lZDDHc32jnqD/ZJSwgbLhq/zWynX+s7TviTHbNI01r3vocguoc3cpPKY4vBss6Kj8XBIIfB7SsttBQGRBzmR57MJqZDjjSyRfgq3Md2gASdCUt7qrprcWsWwyAAg30rt5KNs2qRc5Oa/TerApalu5xoupI900rDoWoPhBYlfSb1xtsDeI7mRcK3J+DX2UFHavvykT72fQ5e++pZXcGizEhHt3LwUGDuEf2TRqhBrsm+eg5UpivmZ+XOg3sngUFHyU1wwX+VwhiyTV8cniEYLksH8rCKCPWCR/2WTMZ7ReqQ0q7rxZWLRF7w0NH3PDDMEr7IkVZ9B7TQzk/XD0hoKduDK5AGNOtq5R1FXm++hMV9Bbbw8gLH5nPpNmZfo+j0sEyvP51UdG+HpKKt8TeZmFzzpSZ3DOQjC1YMVuxqhzZE2ORaNTtGf4twB5+MbKtE=
  on:
    tags: true
  skip_cleanup: true
